EnterDev.TechnicalTest.WebApp/Controllers/AutoController.cs
using EnTerDev.TechnicalTest.Entities.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EnterDev.TechnicalTest.Services.Services;

namespace EnterDev.TechnicalTest.WebApp.Controllers
{
    public class AutoController : Controller
    {
        // GET: Auto
        public ActionResult Index()
        {
            OrchestratorService OrchestratorService = new OrchestratorService();
            List<GroupModel> autos = OrchestratorService.GetGroupsAutos();

            if (TempData["url"] != null)
            {
                ViewBag.Url = TempData["url"];
            }

            return View(autos);
        }

        [HttpGet]
        public ActionResult DownloadFile(string fileName, string idAuto)
        {
            OrchestratorService OrchestratorService = new OrchestratorService();
            string url = OrchestratorService.DownloadFile(fileName, idAuto);
            TempData["url"] = url;

            return RedirectToAction("Index");
        }
    }
}

EnterDev.TechnicalTest.WebApp/Controllers/HomeController.cs
using EnterDev.TechnicalTest.Services.Services;
using EnTerDev.TechnicalTest.Entities.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace EnterDev.TechnicalTest.WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

           
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

   
    }
}

EnterDev.TechnicalTest.WebApp/Views/Auto/Index.cshtml
@model IEnumerable<EnTerDev.TechnicalTest.Entities.Models.GroupModel>

@{
    ViewBag.Title = "Tree View";
}

@if (ViewBag.Url != null)
{
    <script type="text/javascript">
        window.open("@ViewBag.Url", "_blank");
    </script>
}


<h2>Enterdev Technical Test</h2>
<img src="../Resources/logo1.png" style="width:10%;height:15%;">
<ul class="list-group">

    @foreach (var group in Model)
    {
        <li class="list-group-item">
            <span>@Html.DisplayFor(x => group.name)</span>
            <ul>
                @foreach (var auto in group.autoModelList)
                {
                    <li>
                        <span>Name: @Html.DisplayFor(y => auto.name)</span>
                        <ul>
                            <li>
                                <span>File: @Html.DisplayFor(y => auto.file)   </span>
                                @Html.ActionLink("Download", "DownloadFile", "Auto",new { fileName = auto.file, idAuto= auto.auto_id }, new { @class = "btn btn-info btn-xs glyphicon glyphicon-cloud-download" })
                                

                            </li>
                            <li><span>Auto_id: @Html.DisplayFor(y => auto.auto_id)</span></li>
                            <li><span>Realtime: @Html.DisplayFor(y => auto.realtime)</span></li>
                            <li><span>Hash: @Html.DisplayFor(y => auto.hash)</span></li>
                            <li><span>Hidden: @Html.DisplayFor(y => auto.hidden)</span></li>
                            <li><span>Key: @Html.DisplayFor(y => auto.key)</span></li>
                            <li><span>Url: @Html.DisplayFor(y => auto.url)</span></li>
                        </ul>
                    </li>
                }
            </ul>
        </li>
    }
</ul>

EnterDev.TechnicalTest.WebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

EnterDev.TechnicalTest.WebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EnterDev.TechnicalTest.WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "InterDev Technical Test";
}

<div class="jumbotron">
    <img src="../Resources/logo1.png" style="width:10%;height:15%;">
    <h1>Enterdev Technical Test</h1>
    <h4>Luisa Fernanda Franco Jaramillo</h4>
</div>

EnterDev.TechnicalTest.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Enterdev Technical Test ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Auto Tree View", "Index", "Auto")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>